name: Generate changelog and bump up version

on:
  workflow_dispatch:

jobs:
  changelog:
    runs-on: ubuntu-latest
    if: contains('["nattb8", "dom-murray"]', github.actor)

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Generate changelog and bump up version
        uses: TriPSs/conventional-changelog-action@v3
        with:
          skip-git-pull: 'true'
          version-file: './version.yml'
          version-path: 'version'