name: Release to Github Package

on:
  workflow_dispatch:

jobs:
  release-github-package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.PLATFORM_SA_GITHUB_TOKEN }}

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build
        run: ./gradlew imx-core-sdk-kotlin-jvm:build

      - name: Generate changelog and bump up version
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: "${{ secrets.PLATFORM_SA_GITHUB_TOKEN }}"
          skip-git-pull: 'true'
          version-file: './version.yml'
          version-path: 'version'

      - name: Publish to GitHub Packages
        run: ./gradlew publish
        env:
          GPR_USER: ${{ github.actor }}
          GPR_API_KEY: ${{ secrets.PLATFORM_SA_GITHUB_TOKEN }}
