name: Release to Github Package

on:
  pull_request:
    types: [ closed ]

jobs:
  if-release-merged:
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'releases/') == true && github.event.pull_request.merged

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build
        run: ./gradlew imx-core-sdk-android:build

      - name: Publish to GitHub Packages
        run: ./gradlew publish
        env:
          GPR_USER: ${{ github.actor }}
          GPR_API_KEY: ${{ secrets.PLATFORM_SA_GITHUB_TOKEN }}
