name: Release to Github Package

on:
  pull_request:
    branches: ['releases/**']

jobs:
  if-release-merged:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build
        run: ./gradlew imx-core-sdk-android:build

      - name: Publish to GitHub Packages
        run: ./gradlew publish
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.PLATFORM_SA_GITHUB_TOKEN }}
